[package]
name = "aw-client-api"
version = "0.1.0"
edition = "2021"

[dependencies]
aw-rest-api-contract = { path = "../aw-rest-api-contract" }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
